name: notebooks
channels:
  - conda-forge
dependencies:
  - metview-batch
  - cartopy
  - cfgrib
  - cdsapi
  - pip
  - pip:
    - metview=>1.16.1
    - scipy
    - matplotlib
    - xarray
    - pandas
    - netcdf4
    - ecmwf-opendata>=0.3.14
    - ipywidgets
    - ipympl
    - jupyter_contrib_nbextensions
    - jupyterlab
    - nbmake
    - pytest
    - pytest-xdist
    - ecmwf-api-client==1.6.3
